### ISSUE TITLE
Bug: Short and Long Rest buttons have no effect

### ISSUE THREAD

**Issue by WisdomOfWombats** [free-beer/black-sword-hack#7]
Short and Long Rest buttons have no effect. 

Uncaught ReferenceError: ata is not defined
    at takeLongRest (rests.js:12:28)
    at CharacterSheet._onTakeRestClicked (character-sheet.js:306:10)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

-----------------------------------------------------------------------------------
Uncaught TypeError: Cannot read properties of undefined (reading 'system')
    at calculateCharacterData (shared.js:53:19)
    at takeShortRest (rests.js:45:5)
    at CharacterSheet._onTakeRestClicked (character-sheet.js:308:10)
    at HTMLElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)

**Comment by free-beer** [comment]
Fixed in v1.0.2.
